# Generated by Django 2.2.5 on 2019-10-11 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LlojiIndeshjeve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ndeshjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=200)),
                ('data', models.DateField(blank=True, default=datetime.date.today)),
                ('ora', models.TimeField(blank=True, default='17:03')),
                ('ndeshja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.LlojiIndeshjeve')),
            ],
        ),
        migrations.CreateModel(
            name='Regjionet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reshtat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(db_index=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ulset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulsa', models.CharField(max_length=10)),
                ('statusi', models.BooleanField(default=False)),
                ('regjioni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.Regjionet')),
                ('reshti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.Reshtat')),
            ],
        ),
        migrations.CreateModel(
            name='Shitja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura', models.CharField(max_length=10)),
                ('ndeshja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.Ndeshjet')),
                ('ulsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.Ulset')),
            ],
        ),
        migrations.CreateModel(
            name='Cmimet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmimi', models.DecimalField(db_index=True, decimal_places=2, max_digits=6)),
                ('regjioni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.Regjionet')),
                ('reshti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.Reshtat')),
            ],
        ),
    ]
