# Generated by Django 2.2.5 on 2019-11-19 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketerApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regjionet',
            name='hyrja',
            field=models.CharField(blank=True, default='A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ulset',
            name='cordinata',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cmimet',
            name='regjioni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='ticketerApi.Regjionet'),
        ),
        migrations.AlterField(
            model_name='ndeshjet',
            name='data',
            field=models.DateField(blank=True, default='11/20/2019'),
        ),
        migrations.AlterField(
            model_name='ndeshjet',
            name='ora',
            field=models.TimeField(blank=True, default='00:36'),
        ),
    ]
