# Generated by Django 2.2.5 on 2019-12-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketerApi', '0002_auto_20191120_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='shitja',
            name='Cmimet',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.Cmimet'),
        ),
        migrations.AlterField(
            model_name='ndeshjet',
            name='data',
            field=models.DateField(blank=True, default='12/07/2019'),
        ),
        migrations.AlterField(
            model_name='ndeshjet',
            name='ora',
            field=models.TimeField(blank=True, default='15:00'),
        ),
    ]
