# Generated by Django 2.2.5 on 2019-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketerApi', '0003_auto_20191207_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndeshjet',
            name='ora',
            field=models.TimeField(blank=True, default='15:32'),
        ),
        migrations.AlterField(
            model_name='shitja',
            name='Cmimet',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
