# Generated by Django 2.2.5 on 2019-12-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketerApi', '0005_auto_20191207_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndeshjet',
            name='ora',
            field=models.TimeField(blank=True, default='15:37'),
        ),
    ]
