# Generated by Django 2.2.5 on 2019-09-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketerApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulset',
            name='cmimi',
        ),
    ]
