# Generated by Django 2.2.5 on 2019-10-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketerApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlojiIndeshjeve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ndeshjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=200)),
                ('koha', models.DateTimeField()),
                ('ndeshja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.LlojiIndeshjeve')),
            ],
        ),
    ]
