# Generated by Django 2.2.5 on 2019-10-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketerApi', '0002_llojiindeshjeve_ndeshjet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shitja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura', models.CharField(max_length=10)),
                ('ndeshja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.Ndeshjet')),
                ('ulsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketerApi.Ulset')),
            ],
        ),
    ]
